apiVersion: apps/v1
kind: Deployment
metadata:
  name: meudeployment
spec:
  replicas: 2
  selector:
    matchLabels: 
      app: nginx
    template:
      metadata:
        labels: 
          app: nginx
      spec:
        containers:
          - name: site
            image: rodrigosobjak/api-conversao:v1
            ports:
              - containerPort: 80